r"""Hand corrections used by latexify.py.

FIXES          question id -> [(old, new), ...]: exact replacements made in the
               original text before the automatic stages run.  They repair meaning
               that no rule can recover, e.g. an earlier pass that turned
               "4x(1 - x^2)" into "4 \times (1 - x^2)".
COMPUTER_STYLE ids outside the Computer unit whose capital letters are labels, not
               variables (coin outcomes H/T), so only the cautious rules apply.
NO_AUTO        ids to leave entirely to FIXES.
TOPIC_NOTES    the 45 topic-intelligence notes shown under every PYQ answer,
               rewritten with all of their mathematics in LaTeX.
"""

FIXES = {
    # ---- "4x(...)" had become "4 \times (...)"
    '2019-Q20': [
        (r"the $\int 4xy\,dy$ from 0 to 1 is $4 \times (1/2) = 2x$", r"$\int_0^1 4xy\,dy = 4x \cdot \tfrac12 = 2x$"),
        (r"$f_{X}(x) = \int 4xy\,dy = 4x [y^{2}/2]$ from 0 to $1 = 4 \times (1/2) = 2x$",
         r"$f_{X}(x) = \int_0^1 4xy\,dy = 4x\left[y^{2}/2\right]_0^1 = 4x \cdot \tfrac12 = 2x$"),
        (r"Here the $y-\int y$ over $(0,1)$ is $1/2$", r"Here $\int_0^1 y\,dy = 1/2$"),
    ],
    '2019-Q52': [(r"is (leading coefficient) $x n!$, so the answer is abcd $x 10!$.", r"is (leading coefficient) $\times\, n!$, so the answer is $abcd \times 10!$."),
                 (r"equals abcd $x 10!$.", r"equals $abcd \times 10!$.")],
    '2023-Q49': [(r"(leading coefficient) $x n!$", r"(leading coefficient) $\times\, n!$")],
    '2025-Q13': [(r"Intercept = $\mu_{2}$ - slope $x \mu_{1} = 2 - 0.6(2) = 0.8$.", r"Intercept $= \mu_{2} - \text{slope} \times \mu_{1} = 2 - 0.6(2) = 0.8$.")],
    '2018-Q17': [(r"Option (a)'s 22 comes from $4(9) - 5(4) x \ldots$ i.e. from adding variances without squaring the coefficients",
                  r"Option (a)'s 22 comes from $[16(9) - 25(4)]/2 = 22$, i.e. from subtracting the second variance term because its coefficient is negative")],
    '2019-Q59': [(r"- 2 \times (x-1) + 2 \times (x-1)(x-3)", r"- 2x(x-1) + 2x(x-1)(x-3)")],
    '2021-Q04': [
        (r"$f_{X}(x)$ = the $\int 8xy\,dy$ from x to $1 = 4 \times (1 - x^{2})$", r"$f_{X}(x) = \int_x^1 8xy\,dy = 4x(1 - x^{2})$"),
        (r"$f_{X}(x)$ = the integral from $y = x$ to 1 of $8xy dy = 8x[y^{2}/2]$ from x to $1 = 4 \times (1 - x^{2})$",
         r"$f_{X}(x) = \int_{x}^{1} 8xy\,dy = 8x\left[y^{2}/2\right]_x^1 = 4x(1 - x^{2})$"),
        (r"8xy/[4 \times (1-x^{2})]", r"8xy/[4x(1-x^{2})]"),
    ],
    '2021-Q69': [(r"- 6 \times (x-1) + x(x-1)(x-2)", r"- 6x(x-1) + x(x-1)(x-2)")],
    '2026-Q09': [
        (r"2 \times (3x + y)/(2 + y)", r"2x(3x + y)/(2 + y)"),
        (r"2 \times (3x+y)/(2+y)", r"2x(3x+y)/(2+y)"),
        (r"[2y + y^{2}/2]/6$ from 0 to $2 = ", r"\left[2y + y^{2}/2\right]_0^2/6 = "),
        (r"[2x^{3} + x^{2} y]/(2 + y)$ from 0 to $1 = ", r"\left[2x^{3} + x^{2} y\right]_0^1/(2 + y) = "),
    ],
    'FP-053': [(r"6 \times (1 - x)", r"6x(1 - x)"), (r"6 \times (1-x)", r"6x(1-x)")],
    'FP-054': [(r"6 \times (1-x)", r"6x(1-x)")],
    'FS-302': [(r"$6 \times (1-x)$", r"$6x(1-x)$")],
    'FP-222': [(r"6 \times (x^{3}/3)", r"6x(x^{3}/3)")],
    'FP-235': [
        (r"Two branches x = (1 plus or minus $\sqrt{1-y}$)/2", r"Two branches $x = (1 \pm \sqrt{1-y})/2$"),
        (r"Solving $y = 4 \times (1-x)$ gives x = (1 plus or minus $\sqrt{1-y}$)/2.", r"Solving $y = 4x(1-x)$ gives $x = (1 \pm \sqrt{1-y})/2$."),
    ],
    'FP-237': [(r"$4 \times (1-x) > 3/4$", r"$4x(1-x) > 3/4$")],
    # ---- "x" used for a times sign inside formulas
    '2018-Q02': [(r"\right) x \operatorname{P}", r"\right) \times \operatorname{P}"),
                 (r"Hypergeometric x conditional", r"(hypergeometric) $\times$ (conditional)")],
    '2020-Q40': [(r"(share x defect rate)", r"(share $\times$ defect rate)")],
    '2022-Q09': [(r"shape x scale", r"shape $\times$ scale")],
    '2018-Q79': [(r" x ", r" $\times$ ")],
    '2020-Q32': [(r"(\sqrt{n})^{2} x \operatorname{P}(U < 1/n^{2}) = n x 1/n^{2} = 1/n",
                  r"(\sqrt{n})^{2} \times \operatorname{P}(U < 1/n^{2}) = n \times 1/n^{2} = 1/n")],
    '2024-Q19': [(r"(\operatorname{Var} x \operatorname{Var} y)", r"(\operatorname{Var}(x) \operatorname{Var}(y))")],
    '2025-Q04': [(r"\right) x \operatorname{E}(D)", r"\right) \times \operatorname{E}(D)")],
    # ---- integrals whose limits were cut off from the formula
    '2018-Q03': [
        (r"= 1/2 \times 0.5$ + area of the trapezium under $(3-x)/2$ from 2 to $2.5 = 0.25 + 0.1875 = 7/16$",
         r"= \tfrac12 \times 0.5 + \int_{2}^{2.5} \tfrac{3-x}{2}\,dx = 0.25 + 0.1875 = 7/16$"),
        (r"= \int 1/2$ from 1.5 to 2 plus $\int (3-x)/2$ from 2 to $2.5 = 0.25 + ",
         r"= \int_{1.5}^{2} \tfrac12\,dx + \int_{2}^{2.5} \tfrac{3-x}{2}\,dx = 0.25 + "),
        (r"$\int x/2$ over (0,1] = $1/4$; $\int 1/2$ over (1,2] = $1/2$; $\int (3-x)/3$ over (2,3] = $(1/3)(1/2) = 1/6$",
         r"$\int_0^1 \tfrac{x}{2}\,dx = 1/4$; $\int_1^2 \tfrac12\,dx = 1/2$; $\int_2^3 \tfrac{3-x}{3}\,dx = (1/3)(1/2) = 1/6$"),
    ],
    '2018-Q05': [(r"$f_{X}(x)$ = integral over y in $(-1,1)$ of $(1+xy)/4 dy = (1/4)[y + xy^{2}/2]$ from -1 to $1 = (1/4)(2) = 1/2$",
                  r"$f_{X}(x) = \int_{-1}^{1} (1+xy)/4\,dy = (1/4)\left[y + xy^{2}/2\right]_{-1}^{1} = (1/4)(2) = 1/2$")],
    '2018-Q30': [
        (r"integral over $(-1,1)$ of $(1 - r^{2})^{a-1}$ $dr = B(1/2, a)$", r"$\int_{-1}^{1} (1 - r^{2})^{a-1}\,dr = B(1/2, a)$"),
        (r"times the integral over $(-1,1)$ of $(1 - r^{2})^{(N-6)/2}$ dr", r"times $\int_{-1}^{1} (1 - r^{2})^{(N-6)/2}\,dr$"),
    ],
    '2020-Q26': [
        (r"$\operatorname{P}(X \ge 0.4)$ = the integral from 0.4 to $1 = (0.6)^{3} = 0.216$",
         r"$\operatorname{P}(X \ge 0.4) = \int_{0.4}^{1} 3(1-x)^{2}\,dx = (0.6)^{3} = 0.216$"),
        (r"the integral is 6 times the $\int u\,du$ from 0 to $1-x = 6(1-x)^{2}/2 = 3(1-x)^{2}$",
         r"the integral is $6\int_0^{1-x} u\,du = 6(1-x)^{2}/2 = 3(1-x)^{2}$"),
    ],
    '2020-Q28': [
        (r"$M(t)$ = the $\int e^{ty} e^{y}\,dy$ = the $\int e^{(t+1)y}\,dy$ from minus $\infty$ to $0 = 1/(t+1)$",
         r"$M(t) = \int_{-\infty}^{0} e^{ty} e^{y}\,dy = \int_{-\infty}^{0} e^{(t+1)y}\,dy = 1/(t+1)$"),
        (r"the $\int e^{y}$ from minus $\infty$ to 0 is 1", r"$\int_{-\infty}^{0} e^{y}\,dy = 1$"),
        (r"$M_{Y}(t) = \operatorname{E}(e^{tY})$ = the integral from minus $\infty$ to 0 of $e^{ty} e^{y} dy$ = the $\int e^{(t+1)y}\,dy$.",
         r"$M_{Y}(t) = \operatorname{E}(e^{tY}) = \int_{-\infty}^{0} e^{ty} e^{y}\,dy = \int_{-\infty}^{0} e^{(t+1)y}\,dy$."),
        (r"evaluated from minus $\infty$ to 0.", r"evaluated from $-\infty$ to $0$."),
    ],
    '2023-Q18': [(r"Outer integral over y from 1 to $\infty$: the $\int y^{-13}\,dy = [y^{-12}/(-12)]$ from 1 to $\infty = 1/12$.",
                  r"Outer integral over $y$: $\int_1^{\infty} y^{-13}\,dy = \left[y^{-12}/(-12)\right]_1^{\infty} = 1/12$.")],
    '2024-Q32': [
        (r"\operatorname{P}\!\left(\text{X > sqrt t}\right)", r"\operatorname{P}(X > \sqrt{t})"),
        (r"Statement I: the double $\int$ cxy $e^{-(x^{2}+y^{2})}$ over $x, y > 0$ factorises as c times [the $\int x e^{-x^2}\,dx$]^2 = $c(1/2)^{2} = c/4$.",
         r"Statement I: $\int_0^{\infty}\!\int_0^{\infty} cxy\,e^{-(x^{2}+y^{2})}\,dx\,dy = c\left[\int_0^{\infty} x e^{-x^2}\,dx\right]^2 = c(1/2)^{2} = c/4$."),
    ],
    '2024-Q39': [(r"is [$\sqrt{y}$] from 0 to $1 = 1$", r"is $\left[\sqrt{y}\right]_0^1 = 1$")],
    'FP-151': [(r"$\operatorname{E}(X) = (1/2)$[$\int x^{2} e^{-x}\,dx + \int x e^{-x}\,dx$ times 1] = $(1/2)(2 + 1) = 3/2$.",
                r"$\operatorname{E}(X) = \tfrac12\left[\int_0^{\infty} x^{2} e^{-x}\,dx + \int_0^{\infty} x e^{-x}\,dx\right] = (1/2)(2 + 1) = 3/2$.")],
    # ---- sqrt / exp written as words, stray symbols
    '2021-Q10': [(r"the $\Xi$ are", r"the $X_{i}$ are"),
                 (r"these $\Xi$, and $\operatorname{E}(\Xi) = p$", r"these $X_{i}$, and $\operatorname{E}(X_{i}) = p$")],
    '2021-Q34': [(r"$n - 2 = 9$ gives $sqrt = 3$, and $1 - 0.36 = 0.64$ gives $sqrt = 0.8$",
                  r"$n - 2 = 9$ gives $\sqrt{9} = 3$, and $1 - 0.36 = 0.64$ gives $\sqrt{0.64} = 0.8$")],
    '2025-Q52': [(r"\operatorname{P}\!\left(\text{X > sqrt u}\right)", r"\operatorname{P}(X > \sqrt{u})")],
    'FP-347': [(r"\operatorname{E}\!\left(\text{sqrt Y}\right)", r"\operatorname{E}(\sqrt{Y})")],
    'FS-245': [(r"$t_{1} = Z/sqrt$($\chi^{2}$ with 1 degree of freedom)", r"$t_{1} = Z/\sqrt{\chi^{2}_{1}/1}$")],
    'FS-325': [(r"$t_{4} = [(X_{1}+2X_{2})/\sqrt{5}](2)/sqrt$($\chi^{2}$ with 4 degrees of freedom).",
                r"$t_{4} = \dfrac{(X_{1}+2X_{2})/\sqrt{5}}{\sqrt{\chi^{2}_{4}/4}} = \dfrac{2(X_{1}+2X_{2})/\sqrt{5}}{\sqrt{\chi^{2}_{4}}}$.")],
    'FS-353': [(r"$Z/sqrt$($\chi^{2}$ with 1 degree of freedom)", r"$Z/\sqrt{\chi^{2}_{1}/1}$")],
    '2022-Q13': [(r"$\operatorname{E}(e^{W}) = \exp$(mean + variance/2) = $\exp(30 + 150) = e^{180}$",
                  r"$\operatorname{E}(e^{W}) = \exp(\text{mean} + \text{variance}/2) = \exp(30 + 150) = e^{180}$")],
    '2025-Q47': [(r"$M_{Z}(t) = \exp${$\lambda[e^{\lambda(e^{t} - 1)} - 1]$}.", r"$M_{Z}(t) = \exp\{\lambda[e^{\lambda(e^{t} - 1)} - 1]\}$.")],
    'FP-319': [(r"$\exp$(a polynomial)", r"$\exp(\text{a polynomial})$")],
    'FS-077': [(r"$\operatorname{E}(e^{Z}) = \exp$(mean + variance/2)", r"$\operatorname{E}(e^{Z}) = \exp(\text{mean} + \text{variance}/2)$")],
    '2024-Q16': [(r"the $\Gamma$ MGF (1 - scale x t)^(-shape)", r"the $\Gamma$ MGF $(1 - \text{scale} \times t)^{-\text{shape}}$")],
    'FP-076': [(r"The $\Gamma$ MGF is (1 - t/rate)^(-shape);", r"The $\Gamma$ MGF is $(1 - t/\text{rate})^{-\text{shape}}$;")],
    '2025-Q23': [
        (r"$\alpha = (-1)^{9}$/(h * 2h . $\ldots$ . 10h) = $-1/(10! h^{10})$", r"$\alpha = (-1)^{9}/(h \cdot 2h \cdots 10h) = -1/(10!\,h^{10})$"),
        (r"$(-1)^{10}$/(h * 2h . $\ldots$ . 11h) = $1/(11! h^{11})$", r"$(-1)^{10}/(h \cdot 2h \cdots 11h) = 1/(11!\,h^{11})$"),
    ],
    '2022-Q58': [(r"With a common expectation $E, \chi^{2}$ = [sum of $(O - E)^{2}$]/E.",
                  r"With a common expectation $E$, $\chi^{2} = \left[\sum (O - E)^{2}\right]/E$.")],
    '2019-Q03': [
        (r"$\operatorname{CV}$ = (s/mean) x 100%", r"$\operatorname{CV} = (s/\text{mean}) \times 100\%$"),
        (r"$\operatorname{CV} = s$/mean", r"$\operatorname{CV} = s/\text{mean}$"),
        (r"$\operatorname{CV}$(height) = $6.5/115 = 5.65\%$", r"$\operatorname{CV}(\text{height}) = 6.5/115 = 5.65\%$"),
        (r"$\operatorname{CV}$(weight) = $2.7/23 = 11.74\%$", r"$\operatorname{CV}(\text{weight}) = 2.7/23 = 11.74\%$"),
        (r"$\operatorname{CV}2/\operatorname{CV}1 = ", r"$\operatorname{CV}_2/\operatorname{CV}_1 = "),
        (r"$\operatorname{CV}1 = ", r"$\operatorname{CV}_1 = "),
        (r"$\operatorname{CV}2 = ", r"$\operatorname{CV}_2 = "),
    ],
    '2021-Q13': [(r"The $\operatorname{CV}$ = ($\operatorname{SD}$/mean) x 100 is", r"The $\operatorname{CV} = (\operatorname{SD}/\text{mean}) \times 100$ is")],
    'FS-065': [(r"$\operatorname{Var}$(Y given $X = x$)", r"$\operatorname{Var}(Y \mid X = x)$")],
    'FS-090': [(r"$\operatorname{Var}$(Y given $X = x$)", r"$\operatorname{Var}(Y \mid X = x)$")],
    'FP-126': [(r"$\operatorname{E}(1/X)$ = rate/(shape - 1) = $2/2 = 1$", r"$\operatorname{E}(1/X) = \text{rate}/(\text{shape} - 1) = 2/2 = 1$")],
    'FP-122': [(r"$\operatorname{P}(T \le s \mid N(t) = 1) = P$(one event in (0,s], none in (s,t])/$\operatorname{P}(N(t) = 1)$.",
                r"$\operatorname{P}(T \le s \mid N(t) = 1) = \operatorname{P}(\text{one event in } (0,s] \text{ and none in } (s,t]) / \operatorname{P}(N(t) = 1)$.")],
    '2021-Q07': [(r"$\limsup A_{n}$ = the $\bigcap$ the $\bigcup A_{m}$", r"$\limsup A_{n} = \bigcap_{n \ge 1} \bigcup_{m \ge n} A_{m}$")],
    '2020-Q15': [(r"and r = sign(b) $\sqrt{b_{yx} b_{x}y}$", r"and $r = \operatorname{sign}(b)\sqrt{b_{yx} b_{xy}}$")],
    '2022-Q29': [(r"$+1/(x1x_{2})$", r"$+1/(x_{1}x_{2})$")],
    '2022-Q51': [
        (r"$\sum \mid x_{i} - a$| is smallest at a = median", r"$\sum \lvert x_{i} - a\rvert$ is smallest at $a = \text{median}$"),
        (r"is smallest at a = mean.", r"is smallest at $a = \text{mean}$."),
        (r"for any constant $a, \sum \mid x_{i} - a$| attains", r"for any constant $a$, $\sum \lvert x_{i} - a\rvert$ attains"),
    ],
    '2018-Q42': [(r"So A $x^{3} + B x^{2}$ + Cx + $D = A(x^{3} - 6x^{2} + 8x) + B(x^{2} - 2x)$ + Cx + D, which must equal $x^{3}$.",
                  r"So $Ax^{(3)} + Bx^{(2)} + Cx + D = A(x^{3} - 6x^{2} + 8x) + B(x^{2} - 2x) + Cx + D$, which must equal $x^{3}$.")],
    '2023-Q29': [(r"-(coefficient of y)/$(2c) = -(3x - 11)/8 = (11 - 3x)/8$", r"$-(\text{coefficient of } y)/(2c) = -(3x - 11)/8 = (11 - 3x)/8$")],
    '2022-Q48': [(r"mean x (1 - mean)/$(m + n + 1) = ", r"$\text{mean} \times (1 - \text{mean})/(m + n + 1) = ")],
    '2018-Q22': [(r"(X is useless)", r"($X$ is useless)")],
    '2020-Q22': [
        (r"\operatorname{P}({4,5,6})", r"\operatorname{P}(\{4,5,6\})"),
        (r"A = {4,5,6} and B = {1,4}, so A n B = {4} with", r"$A = \{4,5,6\}$ and $B = \{1,4\}$, so $A \cap B = \{4\}$ with"),
        (r"Event A (number greater than 3) = {4, 5, 6}, so", r"Event $A$ (a number greater than 3) is $\{4, 5, 6\}$, so"),
        (r"Event B (perfect square) = {1, 4}, so", r"Event $B$ (a perfect square) is $\{1, 4\}$, so"),
        (r"A intersect B = {4}, with", r"$A \cap B = \{4\}$, with"),
    ],
    '2026-Q16': [(r"Intersection: {$5 < X < 7$} intersect {$X > 6$} = {$6 < X < 7$}, so $P = ",
                  r"Intersection: $\{5 < X < 7\} \cap \{X > 6\} = \{6 < X < 7\}$, so $P = ")],
    'FS-270': [(r"With X = {1, 3, 5} and Y = {2, 4, 6}, what", r"With $X = \{1, 3, 5\}$ and $Y = \{2, 4, 6\}$, what")],
    '2019-Q27': [(r"(N reasonably large)", r"($N$ reasonably large)")],
    # ---- code and binary, not mathematics
    '2020-Q42': [
        (r"such as a + * b are rejected; the apparent exception a * -b is", r"such as $\texttt{a + * b}$ are rejected; the apparent exception $\texttt{a * -b}$ is"),
        (r"as in a + * b, since", r"as in $\texttt{a + * b}$, since"),
        (r"(a * -b is not a counterexample: the minus there is a unary sign attached to b.)",
         r"($\texttt{a * -b}$ is not a counterexample: the minus there is a unary sign attached to $\texttt{b}$.)"),
    ],
    '2022-Q39': [(r"0011 0010 1111 1100 * 0111 0101", r"0011 0010 1111 1100 . 0111 0101")],
    '2018-Q71': [(r"uses $x = x$ % y and", r"uses `x = x % y` and"),
                 (r"the $\sum x + y$ strictly decreases", r"the sum $x + y$ strictly decreases")],
    '2018-Q75': [(r"so that - -x and !!x parse", r"so that `- -x` and `!!x` parse")],
    '2018-Q76': [(r"writing a + b when a - b was intended", r"writing `a + b` when `a - b` was intended")],
    '2025-Q79': [
        (r"$W_{i}-F_{i}$ = IEEE 802.11.", r"Wi-Fi is IEEE 802.11."),
        (r"802.11 Wireless LAN $(W_{i}-F_{i}), 802.15$ Bluetooth/WPAN", r"802.11 Wireless LAN (Wi-Fi), 802.15 Bluetooth/WPAN"),
        (r"$W_{i}-F_{i}$ generations: $802.11b/a/g/n (W_{i}-F_{i} 4)/ac (W_{i}-F_{i} 5)/ax (W_{i}-F_{i} 6)$/be $(W_{i}-F_{i} 7)$.",
         r"Wi-Fi generations: 802.11b, 802.11a and 802.11g, then 802.11n (Wi-Fi 4), 802.11ac (Wi-Fi 5), 802.11ax (Wi-Fi 6) and 802.11be (Wi-Fi 7)."),
        (r"'$W_{i}-F_{i}'$ is a trademark of the $W_{i}-F_{i}$ Alliance", r"'Wi-Fi' is a trademark of the Wi-Fi Alliance"),
        (r"branded $W_{i}-F_{i}$ by the $W_{i}-F_{i}$ Alliance", r"branded Wi-Fi by the Wi-Fi Alliance"),
        (r"none relate to $W_{i}-F_{i}$.", r"none relate to Wi-Fi."),
    ],
    '2024-Q54': [
        (r"the radix $(10's)$ complement", r"the radix (10's) complement"),
        (r"the r's $(10's)$ complement is 100 - n, so $100 - 47 = 53$; the $(r-1)$'$s (9's)$ complement would be",
         r"the $r$'s (10's) complement is $100 - n$, so $100 - 47 = 53$; the $(r-1)$'s (9's) complement would be"),
    ],
    '2026-Q77': [(r"Effective access time = $(1 - p)$ * memory access time + p * page fault service time, where p is the fault rate",
                  r"Effective access time $= (1 - p) \times$ memory access time $+\ p \times$ page-fault service time, where $p$ is the fault rate")],
    '2026-Q62': [(r"single-letter ones (a, b, g, n) are older", r"single-letter ones (802.11a, 802.11b, 802.11g and 802.11n) are older")],
}

COMPUTER_STYLE = {'2020-Q05'}
NO_AUTO = set()


# ------------------------------------------------------------------ topic notes
def _n(pattern, must):
    return {'pattern': pattern, 'mustKnow': must}


TOPIC_NOTES = {
    'P1': _n(r"Two flavours only. (a) Combinatorial or classical counting: round-table seating, splitting $4n$ people into batches, ordered versus unordered samples. (b) Geometric probability: Buffon's needle, a point dropped in a square, the condition for a quadratic to have real roots. Independence-based unions appear as the opening question of a paper.",
             r"For independent events $\operatorname{P}(A_1 \cup \cdots \cup A_n) = 1 - \prod_{i=1}^{n}\{1 - \operatorname{P}(A_i)\}$; inclusion–exclusion; geometric probability is favourable area over total area; ordered samples number $n^{r}$ with replacement and ${}^{n}P_{r}$ without."),
    'P2': _n(r"The urn, agency or factory Bayes template is the single most reliable item in this sub-topic; it appeared in 2018, 2019 (twice), 2023 and 2026. Two other patterns: conditioning that truncates the support of a uniform ($\operatorname{P}(5 < X < 7 \mid X > 6)$ is a trap: the answer is 0, not a ratio of lengths), and Pólya-type urns where the ball is replaced with additions.",
             r"Bayes with unequal priors: $\operatorname{P}(B_k \mid A) = \dfrac{\operatorname{P}(A \mid B_k)\operatorname{P}(B_k)}{\sum_j \operatorname{P}(A \mid B_j)\operatorname{P}(B_j)}$. When conditioning truncates the support, intersect the events first, then divide."),
    'P3': _n(r"Given a piecewise CDF containing an unknown $\alpha$, solve for $\alpha$ or evaluate a probability; the same shell was used twice in one paper (2020-Q33 and 2020-Q36). Also: verifying that a constant makes a function a valid pmf or pdf, and mixed distributions with a jump.",
             r"$F$ is non-decreasing and right-continuous with $F(-\infty) = 0$ and $F(\infty) = 1$; the jump of $F$ at $x$ equals $\operatorname{P}(X = x)$; a valid pdf integrates to 1 over its support."),
    'P4': _n(r"The Poisson approximation to the binomial, the binomial mode and skewness, and waiting-time counting are the workhorses. The negative binomial appears disguised ('the seventh child is the second daughter', 'the first win is on trial $N$'). The hypergeometric shows up as sampling without replacement with a variance ask. The multinomial appears once, as a covariance ask.",
             r"Negative binomial: $\operatorname{P}(X = n) = \binom{n-1}{r-1} p^{r} q^{n-r}$; hypergeometric: $\operatorname{Var}(X) = n\,\dfrac{K}{N}\left(1 - \dfrac{K}{N}\right)\dfrac{N-n}{N-1}$; multinomial: $\operatorname{Cov}(X_i, X_j) = -n p_i p_j$; the binomial mode is $\lfloor (n+1)p \rfloor$."),
    'P5': _n(r"The Beta distribution of the first kind is the recent favourite (its mode, and recovering the parameters from the mean and variance). Also standard: comparing the exponential mean and variance, the Laplace CDF, the Cauchy having no mean, and writing $\operatorname{P}(a \le X \le b)$ for a normal in terms of $\Phi$.",
             r"The Beta-I mode is $\dfrac{a-1}{a+b-2}$ for $a, b > 1$; Laplace: $F(x) = \tfrac12 e^{x}$ for $x < 0$; the Cauchy has no moments; for an exponential with rate $\theta$, $\operatorname{Var}(X) > \operatorname{E}(X)$ if and only if $\theta < 1$."),
    'P6': _n(r"The highest-yield block in Probability (40 items). Modern papers bundle 2–3 questions onto one joint density (2021, 2023, 2025 and 2026 all did this), so one setup can be worth 3 marks. The drill is always the same: the marginal, then a conditional, then a probability over a region, then $\operatorname{E}(XY)$ or a conditional moment. Watch the region: triangular supports ($0 < x < y < 1$) and curved supports ($x^{2} \le y$) are chosen to punish careless limits.",
             r"$f_X(x) = \int f(x,y)\,dy$; $f(y \mid x) = f(x,y)/f_X(x)$; $X$ and $Y$ are independent if and only if $f(x,y)$ factorises and the support is a rectangle; always sketch the region before setting limits."),
    'P7': _n(r"Pure transformation drills, and the same half-dozen results recycle: $X/Y$ for two independent standard normals is Cauchy; $X - Y$ for two i.i.d. exponentials is Laplace; $-\ln X$ for $X \sim U(0,1)$ is exponential; the probability integral transform gives $-\log F(X) \sim \text{Exp}(1)$; $Y = X^{2}$ on $(0,1)$; a sum of i.i.d. exponentials is gamma.",
             r"Jacobian method: $f_Y(y) = f_X\big(g^{-1}(y)\big)\left\lvert \dfrac{d}{dy}\, g^{-1}(y) \right\rvert$. For a non-monotone map, sum over all branches. Memorise the six standard results above."),
    'P8': _n(r"Mostly computational: $\operatorname{E}(XY)$ and the variance of linear combinations from a joint law, conditional expectation from a table or density, and the tower property. A recurring trap is a series whose sum is only conditionally convergent: the question is whether the mean exists at all, not what it equals.",
             r"$\operatorname{Var}(aX+bY) = a^{2} \operatorname{Var}(X) + b^{2} \operatorname{Var}(Y) + 2ab \operatorname{Cov}(X,Y)$; $\operatorname{E}(X) = \operatorname{E}[\operatorname{E}(X\mid Y)]$; $\operatorname{Var}(X) = \operatorname{E}[\operatorname{Var}(X\mid Y)] + \operatorname{Var}[\operatorname{E}(X\mid Y)]$; a mean exists only if $\operatorname{E}\lvert X\rvert < \infty$."),
    'P9': _n(r"Rising sharply: 7 items in 2024 and 5 in 2025. Recurring: identify a distribution from its MGF, the MGF of a linear combination of normals, the pgf $P(s) = \operatorname{E}(s^{X})$, and the compound (random-sum) result $M_{S_N}(t) = M_N(\log M_X(t))$, which was asked in 2024, 2025 and 2026. Characteristic functions of products and ratios also appear.",
             r"$M_{aX+b}(t) = e^{bt} M_X(at)$; the uniqueness theorem; compound sums: $M_{S_N}(t) = M_N(\log M_X(t))$; cumulants: $\kappa_1 = \mu_1'$, $\kappa_2 = \mu_2$, $\kappa_3 = \mu_3$, $\kappa_4 = \mu_4 - 3\mu_2^{2}$."),
    'P10': _n(r"Small but pure theory. Always a constructed counterexample: a sequence that converges in probability but not in mean square, or a limiting CDF that must be checked at the boundaries. Know which implication fails in which direction.",
              r"Almost sure convergence $\Rightarrow$ convergence in probability $\Rightarrow$ convergence in distribution; convergence in mean square $\Rightarrow$ convergence in probability. None of the converses holds without extra conditions (uniform integrability, or a constant limit for distribution $\Rightarrow$ probability)."),
    'P11': _n(r"Only three appearances in nine years, all in 2021–2022, and all recognisable on sight: 'if $\sum \operatorname{P}(A_n) < \infty$, what is $\operatorname{P}(\limsup A_n)$?' and 'does the pattern SFSF occur infinitely often?'. Cheap marks if you know both halves of Borel–Cantelli.",
              r"Borel–Cantelli I: $\sum \operatorname{P}(A_n) < \infty \Rightarrow \operatorname{P}(\limsup A_n) = 0$. Borel–Cantelli II: if the $A_n$ are independent and $\sum \operatorname{P}(A_n) = \infty$, then $\operatorname{P}(\limsup A_n) = 1$."),
    'P12': _n(r"A fixed template: the mean and variance are given, and the answer is a bound with the words 'at least' or 'at most'. It also appears as a sample-size question ('how large must $n$ be so that the probability is at least 0.95'). Spotting 'at least' next to a mean and a variance is the whole skill.",
              r"$\operatorname{P}(\lvert X - \mu\rvert \ge k\sigma) \le 1/k^{2}$, so $\operatorname{P}(\lvert X - \mu\rvert < k\sigma) \ge 1 - 1/k^{2}$. Markov: $\operatorname{P}(X \ge a) \le \operatorname{E}(X)/a$ for $X \ge 0$. Sample size: $n \ge \sigma^{2}/(\varepsilon^{2}\alpha)$."),
    'P13': _n(r"The CLT dressed up as the limit of a binomial sum, consistency of the sample proportion, the CLT applied to sums of squares, and the asymptotic distribution of the empirical CDF. Recognise a sum standardised by $\sqrt{n}$ and you are done.",
              r"CLT: $\dfrac{\sum X_i - n\mu}{\sigma\sqrt{n}} \xrightarrow{d} N(0,1)$. The WLLN needs only a finite mean (Khinchine); the SLLN gives almost-sure convergence."),
    'S1': _n(r"Almost dead: two items in nine years, both conceptual: scales of measurement (nominal, ordinal, interval, ratio) and what counts as data condensation. Do not spend preparation time here beyond knowing the four scales.",
             r"The scales in increasing order of permitted operations are nominal, ordinal, interval and ratio; only the ratio scale has a true zero, so only it permits meaningful ratios."),
    'S2': _n(r"The mean deviation is least about the median; this is asked directly and also embedded in a ratio. Other repeats: the effect of $y = ax + b$ on the mean, SD and MD; comparing the variability of two variables through the coefficient of variation; pooling two groups' means and variances.",
             r"$\operatorname{MD}(ax+b) = \lvert a\rvert \operatorname{MD}(x)$; $\operatorname{SD}(ax+b) = \lvert a\rvert \operatorname{SD}(x)$; $\operatorname{CV} = 100\sigma/\bar{x}$; the combined variance is $\dfrac{n_1(s_1^{2} + d_1^{2}) + n_2(s_2^{2} + d_2^{2})}{n_1 + n_2}$ with $d_i = \bar{x}_i - \bar{x}$, where $\bar{x}$ is the combined mean."),
    'S3': _n(r"Small but consistent: back out $\sigma$ from Pearson's coefficient of skewness, the third central moment of a binomial, recovering $(n, p)$ from $\gamma_1$ and $\gamma_2$, and extracting a fourth central moment from a characteristic function.",
             r"$\operatorname{Sk} = (\text{mean} - \text{mode})/\sigma = 3(\text{mean} - \text{median})/\sigma$; binomial: $\mu_3 = npq(q-p)$ and $\mu_4 = 3n^{2}p^{2}q^{2} + npq(1-6pq)$; $\gamma_1 = \mu_3/\sigma^{3}$ and $\gamma_2 = \mu_4/\sigma^{4} - 3$."),
    'S4': _n(r"$2 \times 2$ attribute tables are the whole topic. Three asks recur: Yule's coefficient of association $Q$, the consistency conditions on class frequencies, and the positive, negative or independent verdict from comparing $(AB)$ with $(A)(B)/N$. The coefficient of contingency from a $\chi^{2}$ value shows up once.",
             r"$Q = (ad - bc)/(ad + bc)$; $A$ and $B$ are independent if and only if $(AB) = (A)(B)/N$; consistency requires every ultimate class frequency to be at least 0; $C = \sqrt{\chi^{2}/(\chi^{2} + N)}$."),
    'S5': _n(r"Thin (3 items) but never absent for long. Orthogonality is the recurring idea: the degree-3 orthogonal polynomial for a standard normal (Hermite), orthogonality checks on pairs of quadratic forms, and choosing between competing least-squares models.",
             r"Orthogonality: $\sum p_i(x)\,p_j(x) = 0$ over the design points for $i \ne j$. Hermite: $H_3(x) = x^{3} - 3x$ for the standard normal weight."),
    'S6': _n(r"Very high yield (26 items) and highly formulaic. The recurring asks are the regression coefficient $b_{yx} = \rho\sigma_y/\sigma_x$, the conditional law of $Y \mid X = x$, independence of $X+Y$ and $X-Y$, $\operatorname{E}[\max(X,Y)]$, $\operatorname{E}(e^{X+Y})$ through the MGF, and the characterisation 'every linear combination is normal'. 2021 and 2023 both ran multi-question BVN clusters.",
             r"$Y \mid X = x \sim N\!\left(\mu_y + \rho\dfrac{\sigma_y}{\sigma_x}(x - \mu_x),\ \sigma_y^{2}(1 - \rho^{2})\right)$; for $\operatorname{BVN}(0,0,1,1,\rho)$, $\operatorname{E}[\max(X,Y)] = \sqrt{(1-\rho)/\pi}$; the MGF is $\exp\!\left(\mathbf{t}'\boldsymbol{\mu} + \tfrac12\,\mathbf{t}'\Sigma\,\mathbf{t}\right)$."),
    'S7': _n(r"The two-regression-lines problem dominates: you are handed two equations and must decide which is which, then extract $r$, and often solve for the means. The validity check is $\lvert r\rvert \le 1$; the wrong assignment gives $\lvert r\rvert > 1$. Regression derived from a joint pdf also appears.",
             r"$b_{yx}\,b_{xy} = r^{2}$; both lines pass through $(\bar{x}, \bar{y})$; $r$ takes the common sign of the two coefficients; $b_{yx} = r\sigma_y/\sigma_x$."),
    'S8': _n(r"The largest topic in Statistical Methods (32 items). The equicorrelated trivariate setup, with all pairwise $r$ equal, is the most repeated single template, asked for both partial and multiple correlation. Also constant: invariance of $r$ under linear transformation (only the sign can change), the range of the intraclass correlation, properties of the correlation ratio, and testing the significance of $r$.",
             r"$r_{12.3} = \dfrac{r_{12} - r_{13}r_{23}}{\sqrt{(1-r_{13}^{2})(1-r_{23}^{2})}}$; $R^{2}_{1.23} = \dfrac{r_{12}^{2} + r_{13}^{2} - 2r_{12}r_{13}r_{23}}{1 - r_{23}^{2}}$; equicorrelated: $R^{2}_{1.23} = 2r^{2}/(1+r)$; the intraclass $r$ lies in $[-1/(k-1),\, 1]$; $\eta^{2} \ge r^{2}$."),
    'S9': _n(r"Standard-error arithmetic: the SE of a proportion, of a mean and of $r$, plus confidence intervals and sample-size determination. Usually one or two easy marks; the formulas are short and the numbers are clean.",
             r"$\operatorname{SE}(\hat{p}) = \sqrt{pq/n}$; $\operatorname{SE}(\bar{x}) = \sigma/\sqrt{n}$; $\operatorname{SE}(r) = (1 - r^{2})/\sqrt{n}$; the 95% CI is $\bar{x} \pm 1.96\,\sigma/\sqrt{n}$."),
    'S10': _n(r"Constructing $t$ and $F$ from independent normals and chi-squares is the signature item: the $C(X_1+X_2)/\sqrt{X_3^{2}+X_4^{2}+X_5^{2}}$ shell appeared in 2018, 2019 and 2025 with only the indices changed. Also recurring: $ns^{2}/\sigma^{2} \sim \chi^{2}_{n-1}$, $\operatorname{E}(X)\operatorname{E}(1/X)$ for an $F$ variate (asked verbatim in 2018 and 2019), and the MGF of $s^{2}$.",
              r"$t_k = Z/\sqrt{V/k}$ with $Z$ and $V$ independent; $F(m,n) = (U/m)/(V/n)$; $(n-1)s^{2}/\sigma^{2} \sim \chi^{2}_{n-1}$; for $F(m,n)$, $\operatorname{E}(X) = n/(n-2)$ and $\operatorname{E}(1/X) = m/(m-2)$; for independent chi-squares $X$ and $Y$, $X/(X+Y)$ is Beta of the first kind and $X/Y$ is Beta of the second kind."),
    'S11': _n(r"Conceptual rather than computational: interpreting Type I and Type II errors, the validity conditions for the $\chi^{2}$ test, choosing the right test for a variance, and getting the degrees of freedom right for an $F$-test of equal variances.",
              r"A Type I error rejects a true $H_0$ (probability $\alpha$); the $\chi^{2}$ test needs independent observations and expected frequencies of at least 5; the $F$-test for two variances uses $(n_1 - 1,\, n_2 - 1)$ d.f.; a test for $\sigma^{2}$ uses $\chi^{2}$."),
    'S12': _n(r"Named-test recognition plus two computations. 'Which non-parametric test is analogous to the $\chi^{2}$ goodness-of-fit test?' was asked verbatim in 2018 and 2022, which is free marks. Computation appears for the KS statistic, the Mann–Whitney $U$ and its variance, and run-test moments.",
              r"$\operatorname{E}(U) = mn/2$ and $\operatorname{Var}(U) = mn(m+n+1)/12$; runs: $\operatorname{E}(R) = 2n_1n_2/n + 1$; $D_n = \sup_x \lvert F_n(x) - F(x)\rvert$; the KS test is the analogue of the $\chi^{2}$ goodness-of-fit test."),
    'S13': _n(r"Steady 1–3 marks every year. The pdf of the minimum, the maximum, the $r$-th order statistic and the sample median, plus expectations for uniform and exponential parents. The minimum of $n$ i.i.d. exponentials being exponential with rate $n\lambda$ is the single most reused fact.",
              r"$g_r(x) = \dfrac{n!}{(r-1)!\,(n-r)!}\, F(x)^{r-1}\,[1-F(x)]^{n-r} f(x)$; the minimum of $n$ i.i.d. $\text{Exp}(\lambda)$ variables is $\text{Exp}(n\lambda)$; for $U(0,1)$, $\operatorname{E}[X_{(r)}] = r/(n+1)$; $\operatorname{P}(X_{(1)} > x) = [1 - F(x)]^{n}$."),
    'S14': _n(r"Asked exactly once in nine years (2021), comparing the sample mean and the sample median as estimators of a normal mean. Learn the one number and move on.",
              r"The ARE of the median relative to the mean at the normal is $2/\pi \approx 0.637$. The ARE is the inverted ratio of asymptotic variances, so the mean is the more efficient estimator here."),
    'N1': _n(r"The single largest topic in the paper (62 items, roughly 7 per paper). Separation of symbols is the engine: everything reduces to $E = 1 + \Delta$. Recurring drills: evaluate $(\Delta^{2}/E) f(x)$; act with $1/(E - a)$ on $a^{x}$-type functions; apply $\Delta^{n}$ to a product of linear or polynomial factors (the answer is $n!$ times the leading coefficient times $h^{n}$, or 0 if the degree is below $n$); differences of zero $\Delta^{n} 0^{m}$; factorial-polynomial conversion; identities for $\delta$ and $\mu$; missing-term problems in an equal-interval table.",
             r"$E = e^{hD}$; $\Delta = E - 1$; $\nabla = 1 - E^{-1}$; $\delta = E^{1/2} - E^{-1/2}$; $\mu = \tfrac12(E^{1/2} + E^{-1/2})$; $\Delta - \nabla = \Delta\nabla$; $\Delta^{n}(a^{x}) = a^{x}(a^{h} - 1)^{n}$; for a polynomial of degree $n$, $\Delta^{n} f = n!\,a_n h^{n}$ and $\Delta^{n+1} f = 0$; $\Delta x^{(n)} = nh\,x^{(n-1)}$."),
    'N2': _n(r"The forward formula for the head of a table, the backward formula for the tail, and one step of extrapolation beyond the last entry. Also: the linear-interpolation error bound and choosing a step size to reach a target accuracy. The table $f(20) = 512$, $f(30) = 439$, $f(40) = 346$, $f(50) = 243$ was reused verbatim in 2020 and 2022.",
             r"Forward: $y = y_0 + p\,\Delta y_0 + \dfrac{p(p-1)}{2!}\,\Delta^{2} y_0 + \cdots$ with $p = (x - x_0)/h$. The backward formula uses $p = (x - x_n)/h$ and $\nabla$. The linear-interpolation error is at most $\dfrac{h^{2}}{8}\max\lvert f''\rvert$."),
    'N3': _n(r"The second-largest numerical topic. The signature item is the $n$-th divided difference of a polynomial: the third divided difference of $x^{3} - 2x$ over the arguments 2, 4, 9, 10 was asked identically in 2019 and 2026. Also constant: the divided difference of $1/x$, symmetry in the arguments, Lagrange with unequal nodes, and truncation-error bounds.",
             r"For a polynomial of degree $n$, $f[x_0, \ldots, x_n] = a_n$ (the leading coefficient) and $f[x_0, \ldots, x_{n+1}] = 0$. For $f(x) = 1/x$, $f[x_0, \ldots, x_n] = (-1)^{n}/(x_0 x_1 \cdots x_n)$. Divided differences are symmetric in their arguments."),
    'N4': _n(r"Thin (4 items) and almost always conceptual: which formula suits which part of the table. Gauss forward or backward near the middle, Stirling for $p$ near 0, Bessel for $p$ near $1/2$.",
             r"Use Stirling when $\lvert p\rvert < 0.25$ and Bessel when $0.25 < p < 0.75$, where $p = (x - x_0)/h$. Gauss's formulas follow the central-difference (zig-zag) path of the difference table."),
    'N5': _n(r"Only two appearances (2019 and 2025). One was a direct table inversion, the other inverted a Lagrange form. Method: swap the roles of $x$ and $y$ and reapply Lagrange, or iterate the forward formula.",
             r"Inverse interpolation by Lagrange: swap the roles of $x$ and $y$, then apply the standard Lagrange formula to get $x$ as a function of $y$. Successive approximation from Newton's forward formula is the alternative."),
    'N6': _n(r"The second-highest numerical topic and the most computational (36 items). Expect a direct Simpson's $1/3$ or trapezoidal evaluation on a supplied table every year, plus one conceptual item on the degree of precision, the number of subintervals each rule requires, or deriving quadrature weights so that the formula is exact to the highest possible order.",
             r"Simpson's $1/3$ rule needs $n$ even and is exact for cubics; Simpson's $3/8$ rule needs $n$ a multiple of 3; Weddle's rule needs $n$ a multiple of 6; the trapezoidal error is $-\dfrac{(b-a)h^{2}}{12}f''(\xi)$; the Simpson $1/3$ error is $-\dfrac{(b-a)h^{4}}{180}f^{(4)}(\xi)$."),
    'N7': _n(r"The thinnest numerical topic (3 items), and both syllabus patterns have now been sampled: recovering $f$ from its first difference (2020 and 2025) and multiplying two geometric series (2026). Cheap marks if you recognise the antidifference.",
             r"$\sum_{x=a}^{b-1} \Delta f(x) = f(b) - f(a)$ (telescoping). To invert $\Delta$ on a polynomial, work in factorial-polynomial form: $\Delta^{-1} x^{(n)} = \dfrac{x^{(n+1)}}{(n+1)h}$."),
    'N8': _n(r"Steady 2–5 marks per paper and rising. Recurring: one or two Euler steps by hand, the absolute-stability interval for forward Euler, successive Picard iterates (first to fourth), and the observation that RK4 applied to $y' = -y$ reproduces the Taylor series up to $h^{4}$.",
             r"Euler: $y_{n+1} = y_n + h f(x_n, y_n)$; absolute stability for $y' = \lambda y$ with real $\lambda < 0$ needs $\lvert 1 + h\lambda\rvert < 1$, i.e. $h < 2/\lvert\lambda\rvert$. Backward Euler is unconditionally stable. RK4 has local error $O(h^{5})$ and global error $O(h^{4})$. Picard: $y_{k+1}(x) = y_0 + \int_{x_0}^{x} f(t, y_k(t))\,dt$."),
    'C1': _n(r"Fetch–decode–execute and the CPU's internal division of labour. Recurring: which unit does what (ALU versus control unit), the main operations of the CPU, BIOS functions, the phases of the machine cycle, the system bus, and RISC versus CISC.",
             r"Machine cycle: fetch, decode, execute, store. The ALU performs arithmetic and logic (AND and OR live here). The control unit directs but does not compute. The BIOS runs the POST and boots the machine."),
    'C2': _n(r"Device classification and one arithmetic item. Know input versus output versus both, the OCR/OMR/MICR trio, CRT internals, and plotter and printer behaviour. The dpi calculation, which multiplies $\text{dpi}^{2}$ by the page area to get the dot count, has appeared as a numerical question.",
             r"Total dots $= \text{dpi}^{2} \times \text{width} \times \text{height}$, with the page measured in inches. MICR reads magnetic-ink characters (banking); OMR reads marks; OCR reads printed characters. A webcam and a light pen are input devices."),
    'C3': _n(r"The memory hierarchy plus address arithmetic. Recurring: RAM versus ROM versus PROM/EPROM, volatile versus non-volatile, where the CPU looks first (cache), registers such as the program counter and the accumulator, virtual memory, and computing either the number of address lines or a total disk capacity.",
             r"Address lines $= \log_2(\text{number of locations})$; disk capacity $=$ surfaces $\times$ tracks $\times$ sectors $\times$ bytes per sector; 1 GB $= 2^{30}$ bytes; ROM, EPROM and flash are non-volatile while DRAM and SRAM are volatile; the accumulator stores ALU results."),
    'C4': _n(r"Base conversion is guaranteed marks every year. The octal 6251 to hexadecimal CA9 item was asked in both 2021 and 2023; the 2's complement of $-59$ in an 8-bit word appeared in both 2022 and 2024. Also: weighted versus non-weighted codes, the largest integer in an $n$-bit word, and normalised floating-point form.",
             r"Octal to hexadecimal through binary: group the bits in threes, then regroup them in fours. 2's complement $=$ 1's complement $+\,1$. The largest unsigned value in $n$ bits is $2^{n} - 1$ and the largest signed value is $2^{n-1} - 1$. BCD (8421) is weighted; Gray and ASCII are not."),
    'C5': _n(r"Operating-system concepts, broadly. Recurring: OS functions and goals, real-time versus embedded versus batch versus time-sharing, the kernel as the core of UNIX (asked in 2018 and again in 2023), the four deadlock conditions, process states, and page faults.",
             r"Deadlock needs mutual exclusion, hold-and-wait, no pre-emption and circular wait, all four. Process states: new, ready, running, waiting, terminated. Firmware lives in ROM. Linux is open source; Windows CE is embedded."),
    'C6': _n(r"Translators and language levels. The compiler-versus-interpreter distinction is asked in some form nearly every year: a compiler translates the whole program and then runs it, an interpreter translates and executes line by line. Also: linker versus loader, the lexical analyser's output, and which errors are detectable.",
             r"Compilers and interpreters detect syntax and semantic errors but not logical errors; a program with a logical error still runs. The lexical analyser outputs a stream of tokens. Assembly and machine language are low-level."),
    'C7': _n(r"The biggest computer topic (29 items). Layer-mapping questions dominate: ICMP and ARP at the network layer, SMTP, FTP and HTTP at the application layer. ARP resolving an IP address to a MAC address was asked in both 2021 and 2026. Also: topology failure behaviour, DNS, port numbers, transmission media, IEEE 802.11 and connecting devices.",
             r"ARP maps an IP address to a MAC address; DNS maps a name to an IP address. Ports: FTP 21, SMTP 25, HTTP 80, POP3 110, IMAP 143. In a star topology only the hub is a single point of failure; a ring breaks on any single node failure. The brand name WiFi refers to IEEE 802.11."),
    'C8': _n(r"Threat taxonomy plus firewall concepts. Know precisely what separates a virus, a worm, a trojan and spyware; the discriminator is usually whether user action is needed to spread (a worm needs none). Phishing appears as a short scenario. Firewall terminology and packet filtering recur.",
             r"A worm self-propagates with no user interaction; a virus needs a host and user action. A polymorphic virus rewrites its own code to evade detection. Non-repudiation stops a sender denying a transmission. ISO 27001 is the information-security management standard."),
    'C9': _n(r"Programming fundamentals, tested conceptually. Recurring: debugging (breakpoints and the order of the debugging steps), flowcharts, arrays and strings, subroutines and modularity, operator precedence and associativity, bitwise operators, stable sorting algorithms, and tracing a short loop.",
             r"Stable sorts: bubble, insertion and merge; quicksort and heapsort are not stable. Unary and assignment operators associate right to left. `&&` and `!` are logical, not bitwise; `&`, `|`, `^`, `>>` and `<<` are bitwise. Space complexity is the memory an algorithm requires."),
    'C10': _n(r"Databases plus file-format literacy. The hierarchical (tree) data model was asked in both 2021 and 2024. Also: DBMS advantages, SQL capabilities, the ACID properties, client–server architecture, and classifying raster image, audio and multimedia formats.",
              r"ACID: Atomicity, Consistency, Isolation, Durability (security is not one of them). Hierarchical model: tree; network model: graph. Raster formats: JPEG, GIF, PNG, BMP. Vector: SVG. Audio: WAV, MP3, WMA (TIFF and MPEG video are not audio)."),
}
